### ISSUE TITLE
NameError: name 'data' is not defined for Windows aggmap

### ISSUE THREAD

**Issue by shenwanxiang** [shenwanxiang/bidd-aggmap#20]
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\AdminCOOP\anaconda3\envs\aggmap\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\AdminCOOP\anaconda3\envs\aggmap\lib\site-packages\aggmap\utils\calculator.py", line 41, in _fuc
    return _calculate(i1, i2)
  File "C:\Users\AdminCOOP\anaconda3\envs\aggmap\lib\site-packages\aggmap\utils\calculator.py", line 23, in _calculate
    x1 = data[:, i1]
NameError: name 'data' is not defined
"""

The above exception was the direct cause of the following exception:

**Comment by shenwanxiang** [comment]
You shouldn't expect the values of global variables that you set in the parent process to be automatically propagated to the child processes.

Your code happens to work on Unix-like platforms because on those platforms multiprocessing uses [fork()](http://en.wikipedia.org/wiki/Fork_%28operating_system%29). This means that every child processes gets a copy of the parent process's address space, including all global variables.

This isn't the case on Windows; every variable from the parent process that needs to be accessed by the child has to be explicitly [passed down or placed in shared memory](http://docs.python.org/dev/library/multiprocessing.html#sharing-state-between-processes).

Once you do this, your code will work on both Unix and Windows.

Ref: https://stackoverflow.com/questions/6596617/python-multiprocess-diff-between-windows-and-linux
